<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Meja extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Meja_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $meja = $this->Meja_model->get_all();

        $data = array(
            'meja_data' => $meja
        );

        $this->template->load('template','tbl_meja_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Meja_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_meja' => $row->id_meja,
		'nama_meja' => $row->nama_meja,
		'lokasi_meja' => $row->lokasi_meja,
	    );
            $this->template->load('template','tbl_meja_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('meja'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('meja/create_action'),
	    'id_meja' => set_value('id_meja'),
	    'nama_meja' => set_value('nama_meja'),
	    'lokasi_meja' => set_value('lokasi_meja'),
	);
        $this->template->load('template','tbl_meja_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_meja' => $this->input->post('nama_meja',TRUE),
		'lokasi_meja' => $this->input->post('lokasi_meja',TRUE),
	    );

            $this->Meja_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('meja'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Meja_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('meja/update_action'),
		'id_meja' => set_value('id_meja', $row->id_meja),
		'nama_meja' => set_value('nama_meja', $row->nama_meja),
		'lokasi_meja' => set_value('lokasi_meja', $row->lokasi_meja),
	    );
            $this->template->load('template','tbl_meja_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('meja'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_meja', TRUE));
        } else {
            $data = array(
		'nama_meja' => $this->input->post('nama_meja',TRUE),
		'lokasi_meja' => $this->input->post('lokasi_meja',TRUE),
	    );

            $this->Meja_model->update($this->input->post('id_meja', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('meja'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Meja_model->get_by_id($id);

        if ($row) {
            $this->Meja_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('meja'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('meja'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_meja', 'nama meja', 'trim|required');
	$this->form_validation->set_rules('lokasi_meja', 'lokasi meja', 'trim|required');

	$this->form_validation->set_rules('id_meja', 'id_meja', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Meja.php */
/* Location: ./application/controllers/Meja.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-31 09:04:59 */
/* http://harviacode.com */