<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tms_edc_model extends CI_Model
{

    public $table = 'tbl_tms_edc';
    public $id = 'id_tms';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_tms', $q);
	$this->db->or_like('sn_edc_lama', $q);
	$this->db->or_like('sn_edc_baru', $q);
	$this->db->or_like('merk_lama', $q);
	$this->db->or_like('merk_baru', $q);
	$this->db->or_like('spk_edc_lama', $q);
	$this->db->or_like('spk_edc_baru', $q);
	$this->db->or_like('no_simcard_lama', $q);
	$this->db->or_like('no_simcard_baru', $q);
	$this->db->or_like('sn_simcard_lama', $q);
	$this->db->or_like('sn_simcard_baru', $q);
	$this->db->or_like('sn_clr_lama', $q);
	$this->db->or_like('sn_clr_baru', $q);
	$this->db->or_like('sam_brizzi_lama', $q);
	$this->db->or_like('sam_brizzi_baru', $q);
	$this->db->or_like('tid_lama', $q);
	$this->db->or_like('tid_baru', $q);
	$this->db->or_like('mid_lama', $q);
	$this->db->or_like('mid_baru', $q);
	$this->db->or_like('nama_agen_lama', $q);
	$this->db->or_like('nama_agen_baru', $q);
	$this->db->or_like('alamat_agen_lama', $q);
	$this->db->or_like('alamat_agen_baru', $q);
	$this->db->or_like('cabang_lama', $q);
	$this->db->or_like('cabang_baru', $q);
	$this->db->or_like('branch_lama', $q);
	$this->db->or_like('branch_baru', $q);
	$this->db->or_like('kode_uker_lama', $q);
	$this->db->or_like('kode_uker_baru', $q);
	$this->db->or_like('norek_lama', $q);
	$this->db->or_like('norek_baru', $q);
	$this->db->or_like('jenis_edc_lama', $q);
	$this->db->or_like('jenis_edc_baru', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tms', $q);
	$this->db->or_like('sn_edc_lama', $q);
	$this->db->or_like('sn_edc_baru', $q);
	$this->db->or_like('merk_lama', $q);
	$this->db->or_like('merk_baru', $q);
	$this->db->or_like('spk_edc_lama', $q);
	$this->db->or_like('spk_edc_baru', $q);
	$this->db->or_like('no_simcard_lama', $q);
	$this->db->or_like('no_simcard_baru', $q);
	$this->db->or_like('sn_simcard_lama', $q);
	$this->db->or_like('sn_simcard_baru', $q);
	$this->db->or_like('sn_clr_lama', $q);
	$this->db->or_like('sn_clr_baru', $q);
	$this->db->or_like('sam_brizzi_lama', $q);
	$this->db->or_like('sam_brizzi_baru', $q);
	$this->db->or_like('tid_lama', $q);
	$this->db->or_like('tid_baru', $q);
	$this->db->or_like('mid_lama', $q);
	$this->db->or_like('mid_baru', $q);
	$this->db->or_like('nama_agen_lama', $q);
	$this->db->or_like('nama_agen_baru', $q);
	$this->db->or_like('alamat_agen_lama', $q);
	$this->db->or_like('alamat_agen_baru', $q);
	$this->db->or_like('cabang_lama', $q);
	$this->db->or_like('cabang_baru', $q);
	$this->db->or_like('branch_lama', $q);
	$this->db->or_like('branch_baru', $q);
	$this->db->or_like('kode_uker_lama', $q);
	$this->db->or_like('kode_uker_baru', $q);
	$this->db->or_like('norek_lama', $q);
	$this->db->or_like('norek_baru', $q);
	$this->db->or_like('jenis_edc_lama', $q);
	$this->db->or_like('jenis_edc_baru', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tms_edc_model.php */
/* Location: ./application/models/Tms_edc_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-31 04:02:17 */
/* http://harviacode.com */